[package]
name = "star-fighter"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-node-v1.8.0'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-node-v1.8.0'
subdir = 'aptos-move/framework/aptos-token-objects'

[dependencies.MoveStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-node-v1.8.0'
subdir = 'aptos-move/framework/move-stdlib'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-node-v1.8.0'
subdir = 'aptos-move/framework/aptos-token'

[dependencies.AptosStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-node-v1.8.0'
subdir = 'aptos-move/framework/aptos-stdlib'

[addresses]
star_fighter = "_"

[dev-addresses]
star_fighter = "0x123"
